### PR TITLE
Updates 1 word in ReadMe - Removes ambiguity

### PR DESCRIPTION
**Pull request by AmitaiB**
This pull request has been automatically created by learn.co.

### CODE REVIEW

**Comment by markedwardmurray** [comment]
i don't really see "Arrays + Loops" as less ambiguous than "Arrays with Loops". what about the section title confused you?

**Comment by AmitaiB** [comment]
I think it was because “Arrays+Loops” made me think of a Category on
Arrays. But you’re right, “Arrays with Loops” is also rather ambiguous.
That section is about iterating over arrays, right? How do you like
“Iterating Over Arrays”?

Amitai

**Comment by markedwardmurray** [comment]
I think I'm just gonna leave it like it is as "arrays with loops" for the time being, mostly cuz I'm lazy. Let me know if you find anything else that's unclear.

**Comment by AmitaiB** [comment]
Laziness is an adaptive trait critical to the past evolution and future survival of the human species. All power to ya. :)

**Pull request closed without merging**
